<template>
  <div class="hello">
    <h>{{ $route.name }}</h>
    <div class="testRotate">nihao</div>
    <HiHi></HiHi>
  </div>
</template>

<script>
import HiHi from "@/components/HiHi.vue";

export default {
  components: { HiHi },
  name: "TestFirst",
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}

.testRotate {
  animation: rotate-top 2s cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-2-21 18:50:33
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-top
 * ----------------------------------------
 */
@keyframes rotate-top {
  0% {
    transform: rotate(0);
    transform-origin: top;
  }
  30% {
    transform: rotate(360deg);
    transform-origin: top;
  }
  60% {
    transform: rotate(0);
    transform-origin: top;
  }
  100% {
    transform: rotate(360deg);
    transform-origin: top;
  }
}
</style>
